package com.example.ecommerce.enums;

public enum ToStatus {

    CANCELLED(1,FromStatus.ORDER_PLACED),
    ORDER_CONFIRMED(2,FromStatus.ORDER_PLACED),
    ORDER_REJECTED(3,FromStatus.ORDER_PLACED),
    REFUND_INITIATED(4,FromStatus.CANCELLED),
    CLOSED(5,FromStatus.CANCELLED),
    REFUND_INITIATED_ORDER_REJECTED(6,FromStatus.ORDER_REJECTED),
    CLOSED_ORDER_REJECTED(7,FromStatus.ORDER_REJECTED),
    CANCELLED_ORDER_CONFIRMED(8,FromStatus.ORDER_CONFIRMED),
    ORDER_SHIPPED(9,FromStatus.ORDER_CONFIRMED),
    DELIVERED(10,FromStatus.ORDER_SHIPPED),
    RETURN_REQUESTED(11,FromStatus.DELIVERED),
    CLOSED_DELIVERY(12,FromStatus.DELIVERED),
    RETURN_REJECTED(13,FromStatus.RETURN_REQUESTED),
    RETURN_APPROVED(14,FromStatus.RETURN_REQUESTED),
    CLOSED_RETURN_REJECTED(15,FromStatus.RETURN_REJECTED),
    PICKUP_INITIATED(16,FromStatus.RETURN_APPROVED),
    PICKUP_COMPLETED(17,FromStatus.PICK_UP_INITIATED),
    PICKUP_REFUND_INITIATED(18,FromStatus.PICK_UP_COMPLETED),
    PICKUP_REFUND_COMPLETED(19,FromStatus.REFUND_INITIATED),
    CLOSED_REFUND_COMPLETED(20,FromStatus.REFUND_COMPLETED);


    ToStatus(int i,FromStatus status){
    }


}
